// Define type for Lead Column
export type LeadColumn = {
  UserFacingName: string;
  mappings: string[];
  ColumnNameInSheet: string;
  dbName: string;
};

export const LeadDefaultColumns = {
  firstName: {
    UserFacingName: "First Name",
    mappings: [
      "first name",
      "firstname",
      "name",
      "client name",
      "fullname",
      "full name",
      "username",
      "user name",
      "given name",
      "person name",
      "employee name",
      "contact",
      "contact name",
      "customer",
      "prospect",
      "prospect name",
      "suspect",
      "suspect name",
      "customer name",
    ],
    ColumnNameInSheet: "",
    dbName: "firstName",
  },
  lastName: {
    UserFacingName: "Last Name",
    mappings: ["last name", "lastname", "name", "surname", "family name"],
    ColumnNameInSheet: "",
    dbName: "lastName",
  },
  email: {
    UserFacingName: "Email",
    mappings: ["email", "email address", "mail", "gmail"],
    ColumnNameInSheet: "",
    dbName: "email",
  },
  phone: {
    UserFacingName: "Phone Number",
    mappings: [
      "cell no",
      "cell",
      "phone no",
      "phone",
      "phone number",
      "number",
      "contact",
      "contact number",
      "mobile",
      "mobile number",
      "home phone",
      "work phone",
      "office phone",
      "user phone",
      "employee phone",
      "telephone",
      "telephone number",
    ],
    ColumnNameInSheet: "",
    dbName: "phone",
  },
  address: {
    UserFacingName: "Address",
    mappings: ["address", "location", "address line"],
    ColumnNameInSheet: "",
    dbName: "address",
  },
} as const;

export const LeadDefaultColumnsArray: LeadColumn[] = [
  {
    UserFacingName: "First Name",
    mappings: [
      "first name",
      "firstname",
      "name",
      "fullname",
      "full name",
      "client name",
      "username",
      "user name",
      "given name",
      "person name",
      "employee name",
      "contact",
      "contact name",
      "customer",
      "prospect",
      "prospect name",
      "suspect",
      "suspect name",
      "customer name",
    ],
    ColumnNameInSheet: "",
    dbName: "firstName",
  },
  {
    UserFacingName: "Last Name",
    mappings: ["last name", "lastname", "surname", "family name"],
    ColumnNameInSheet: "",
    dbName: "lastName",
  },
  {
    UserFacingName: "Email",
    mappings: ["email", "email address", "mail"],
    ColumnNameInSheet: "",
    dbName: "email",
  },
  {
    UserFacingName: "Phone Number",
    mappings: [
      "cell no",
      "cell",
      "phone no",
      "phone",
      "phone number",
      "number",
      "contact",
      "contact number",
      "mobile",
      "mobile number",
      "home phone",
      "work phone",
      "office phone",
      "user phone",
      "employee phone",
      "telephone",
      "telephone number",
    ],
    ColumnNameInSheet: "",
    dbName: "phone",
  },
  {
    UserFacingName: "Address",
    mappings: ["address", "location", "address line"],
    ColumnNameInSheet: "",
    dbName: "address",
  },
];
