import localFont from "next/font/local";
import "./globals.css";
import type { Metadata } from "next";
import React, { ReactNode } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "AgentX",
  description: "Generated by e8-labs",
  manifest: "/manifest.json",
  openGraph: {
    title: "Create Your AI Agent - AgentX",
    description: "Design and create custom AI agents with ease.",
    url: "https://ai.myagentx.com/",
    images: [
      {
        url: "https://ai.myagentx.com/thumbOrbSmall.png",
        width: 276,
        height: 276,
        alt: "Thumbnail Alt Text",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Create Your AI Agent - AgentX",
    description: "Design and create custom AI agents with ease.",
    images: ["https://ai.myagentx.com/thumbOrb.png"],
  },
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Edu+AU+VIC+WA+NT+Arrows:wght@400..700&display=swap"
          rel="stylesheet"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ fontFamily: "Inter" }}
      >
        {children}
      </body>
    </html>
  );
}
